update go

diff --git a/bash/backup_script/script b/bash/backup_script/script
--- a/bash/backup_script/script
+++ b/bash/backup_script/script
@@ -2,8 +2,8 @@
 
 # check for input argument
 if [ -z "$1" ]; then
-	echo "Usage: $0 <file_or_directory_to_backup>"
-	exit 1
+    echo "Usage: $0 <file_or_directory_to_backup>"
+    exit 1
 fi
 
 input_obj_path=$(realpath "$1")
@@ -25,14 +25,14 @@ NC='\033[0m' # No Color
 # check input_obj type and coping data
 # depends on obj type.
 if [ -f "$input_obj" ]; then
-	echo -e "${YELLOW}Backing up file: ${NC}$input_obj"
-	cp "$input_obj_path" "$backup_folder_path/${input_obj}_$date_now"
-	echo -e "${GRN}Backup complete.👌"
+    echo -e "${YELLOW}Backing up file: ${NC}$input_obj"
+    cp "$input_obj_path" "$backup_folder_path/${input_obj}_$date_now"
+    echo -e "${GRN}Backup complete.👌"
 elif [ -d "$input_obj" ]; then
-	echo -e "${YELLOW}Backing up directory: ${NC}$input_obj"
-	cp -r "$input_obj_path" "$backup_folder_path/${input_obj}_$date_now"
-	echo -e "${GRN}Backup complete.👌"
+    echo -e "${YELLOW}Backing up directory: ${NC}$input_obj"
+    cp -r "$input_obj_path" "$backup_folder_path/${input_obj}_$date_now"
+    echo -e "${GRN}Backup complete.👌"
 else
-	echo "Error: $input_obj does not exist or is not a regular file/directory"
-	exit 2
+    echo "Error: $input_obj does not exist or is not a regular file/directory"
+    exit 2
 fi
